Sprint 13
pitinovamargo/ImageFeed pull request #6
Opened 2023-06-14 13:19 UTC by pitinovamargo

2023-06-14 20:42 UTC, protos17 requested changes

2023-06-14 20:42 UTC, protos17 commented on Image Feed Tests/WebViewPresenterSpy.swift
> +import ImageFeed
Дя тестов необходимо импортировать так:

@testable import ImageFeed

2023-06-14 20:42 UTC, protos17 commented on Image Feed Tests/WebViewViewControllerSpy.swift
> +import ImageFeed
Здесь тоже заменить на @testable import ImageFeed

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/AuthConfiguration.swift
> +    init(accessKey: String, secretKey: String, redirectURI: String, accessScope: String, authURLString: String, defaultBaseURL: URL) {
Для структур можно не писать инициализатор

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/AuthConfiguration.swift
> +let fileAccessKey = "5damU5G0-RGi6CU4KhEzI8_i7VSBJa3wEYGxz1rnl3k"
Рекомендую вынести их в структуру или enum и обращаться через static let

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/AuthHelper.swift
> +class AuthHelper: AuthHelperProtocol {
Рекомендую указать как final

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/AuthHelper.swift
> +    let configuration: AuthConfiguration
Рекомендую указать как private

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
>      let showWebViewIdentifier = "ShowWebView"
рекомендую указать как private

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/AuthViewController.swift
> +            else { fatalError("Failed to prepare for WebViewViewController") }
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/OAuth2Service.swift
>          var urlComponents = URLComponents(string: "https://unsplash.com/oauth/token")!
Рекомендую перенести в константы

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/SplashViewController.swift
> +                        print("FAIL IMAGE FETCH")
Рекомендую вместо print использовать assertionFailure:

case .failure(let error):
assertionFailure(error.localizedDescription)

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/WebViewPresenter.swift
> +    var authHelper: AuthHelperProtocol
Рекомендую указать как private let

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +public protocol WebViewViewControllerProtocol: AnyObject {
Рекомендую убрать public

2023-06-14 20:42 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
> +            let indexPath = sender as! IndexPath
Не рекомендую использовать принудительное извлечение опционалов, лучше сделать проверку через guard let

2023-06-14 20:42 UTC, protos17 commented on ImageFeedUITests/ImageFeedUITests.swift
> +    let email = ""
Отличное решение, молодец!

2023-06-14 20:42 UTC, protos17 commented on ImageFeedUITests/ImageFeedUITests.swift
> +        app.tap()
Необходимо убрать эту строку, чтобы не пытался нажимать на кнопку входа без введенного пароля

2023-06-14 20:42 UTC, protos17 commented on ImageFeedUITests/ImageFeedUITests.swift
> +        app.alerts["bye_bye"].scrollViews.otherElements.buttons["logout_yes"].tap()
После этого необходимо добавить проверку, что открылся экран авторизации

2023-06-14 21:15 UTC, pitinovamargo commented on ImageFeedUITests/ImageFeedUITests.swift
> +        app.tap()
эта строка убирает экранную клавиатуру, щелкая в пустом месте приложения. без этого приложение не может перейти в поле с вводом пароля из-за клавиатуры

2023-06-14 21:16 UTC, protos17 commented on ImageFeedUITests/ImageFeedUITests.swift
> +        app.tap()
Там дальше свайп идет, который скроет клавиатуру

2023-06-14 21:52 UTC, pitinovamargo commented on ImageFeedUITests/ImageFeedUITests.swift
> +        app.tap()
к сожалению, свайп не закрывает клавиатуру (пыталась по-разному много раз) и каждый раз падает из-за этого на этом моменте. пока заработал следующий способ: app.toolbars.buttons["Done"].tap() могу ли я его использовать?

2023-06-14 21:53 UTC, protos17 commented on ImageFeedUITests/ImageFeedUITests.swift
> +        app.tap()
Да, это самый правильный вариант, молодец!

2023-06-15 20:05 UTC, protos17 approved these changes

2023-06-15 20:05 UTC, protos17 commented on ImageFeed/Auth/SplashViewController.swift
> +        oauthService.fetchAuthToken(code) { result in
Здесь тоже сильная ссылка, необходимо добавить weak self

2023-06-15 20:05 UTC, protos17 commented on ImageFeed/Profile/ProfileViewController.swift
Здесь во view.didLoad рекомендую указать цвет фона:

view.backgroundColor = .ypBlack

2023-06-15 20:05 UTC, protos17 commented on ImageFeed/Profile/ProfileViewController.swift
>      @objc func profileLogout() {
Рекомендую указать как private

2023-06-15 20:05 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListViewController.swift
>              let viewController = segue.destination as! SingleImageViewController
здесь тоже рекомендую убрать forceUnwrap

2023-06-15 20:05 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListService.swift
> +                        print("Error decoding JSON: \(error)")
Рекомендую заменить на assertionFailure

2023-07-07 14:37 UTC, merged